import os

PROJECT_DIR = os.path.dirname(os.path.realpath(__file__))
DATA_DIR = PROJECT_DIR + "/data/"
MODEL_DIR = PROJECT_DIR + "/models/"

# DEFAULT NEURAL NETWORK CONFIGURATION

LSTM_OPTIMIZER = 'adam'
LSTM_EPOCHS = 50
LSTM_PATIENCE = 5  # Early Stopping
LSTM_LOSS_FUNCTION = 'mean_squared_error'
WINDOW_SIZE = 14
NUM_CELLS_LSTM = 100
BATCH_SIZE = 128
VERBOSE = 0
NUM_LAYERS = 3
LSTM_VALIDATION_SPLIT = 0.1
LSTM_DROPOUT = 0.1
LSTM_RECURRENT_DROPOUT = 0.1
LSTM_TRAIN_TEST_SPLIT = 0.85
FEATURE_DIMENSION = 3  # FEATURE TO BE FORECASTED, HOUR AND MINUTE
OUTPUT_DIMENSION = 1
EARLY_STOP_METRIC = 'val_loss'


# RETRAINING CRITERIA CONFIGURATION
MAX_AGE = 30  # DAYS
MAX_ANOMALIES_PER_HOUR = 5  # MAX NUMBER OF DATA POINTS IN AN HOUR IS 6 (1 PER 10 MIN)


# PARALLELISM CONTROLLER
INTRA_OP_PARALLELISM_THREADS = 1  # RECOMMENDED VALUE: SET IT EQUAL TO NUMBER OF PHYSICAL CORES
INTER_OP_PARALLELISM_THREADS = 1  # RECOMMENDED VALUE: SET IT EQUAL TO NUMBER OF PHYSICAL CORES


# ANOMALY DETECTION PARAMETER
K = 2  # FOR CONTROLLING MIN_MAX BOUNDS. BOUNDS ARE GIVEN BY "B = DATA +- K*STD"
